### ISSUE TITLE
Update to Subsonic 5.3

### ISSUE THREAD

**Issue by mbirth** [hurricanehrndz/docker-subsonic#1]
Please update the `install.sh` to Subsonic 5.3. The download link is:

`http://subsonic.org/download/subsonic-5.3.deb`

**Comment by hurricanehrndz** [comment]
Okay.

**Comment by hurricanehrndz** [comment]
This has been done, sorry for the delay.

**Comment by mbirth** [comment]
Awesome! Many thanks!

**Comment by mbirth** [comment]
I noticed the listing on [DockerHub](https://hub.docker.com/r/hurricane/docker-subsonic/) didn't update itself. Do you have to trigger that manually?

**Comment by hurricanehrndz** [comment]
Done.
