### ISSUE TITLE
Subsonic 6.0beta1 update

### ISSUE THREAD

**Issue by jasii** [hurricanehrndz/docker-subsonic#3]
@hurricanehrndz I wasn't sure how to post this since I'm new to this whole github thing. I hope this "issues" area is an okay place. A new 6.0beta1 is out. Could you please update to the latest? Thanks for the docker container btw. Been running it for a few months now with no issues.

**Comment by hurricanehrndz** [comment]
Jasii,

This is perfect place to voice your request. I can not upgrade the current
docker image to 6.0beta. The current docker image is supposed to track
stable releases.  I will however creat a new branch for your request and
create a new unraid template that will track beta releases rather then
stable

**Comment by jasii** [comment]
Thank you @hurricanehrndz 

Let me know if there is anything I could help you with!

**Comment by hurricanehrndz** [comment]
I should have something ready by Tuesday.

**Comment by jasii** [comment]
Thanks! Looking forward to trying it out

**Comment by jasii** [comment]
Are you having trouble getting it working?

**Comment by hurricanehrndz** [comment]
Nope, not at all. Just backed up with a crap of auto update features I'm
including.

**Comment by hurricanehrndz** [comment]
I'm almost done, unfortunately I'm going away on a snowboarding trip and will not be able to finish until Monday. Anyhow, you can see the work that has gone into it so far here:
https://github.com/hurricanehrndz/docker-containers/tree/master/subsonic

List of new features and fixes:
- Automatic Updates 
- Latest JDK
- Automatic build on new releases
- Better documentation
- Tumbleweed base
- Wrapper script and systemd service file for non unRAID installs
- Update script that can be executed via docker exec

**Comment by jasii** [comment]
Wow man, thanks for all your hard work! Have a great trip!

**Comment by hurricanehrndz** [comment]
New docker has been built: https://hub.docker.com/r/hurricane/subsonic/

You can find the new template [here](https://github.com/hurricanehrndz/container-templates/tree/master/hurricane) name Subsonicbeta.xml. 

Please open any issues in that project.
